# Generated by Django 3.0.8 on 2020-08-29 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200829_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follower_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
