# Generated by Django 3.0.8 on 2020-09-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200910_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='Single', max_length=32),
        ),
    ]
