# Generated by Django 3.0.8 on 2020-09-16 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20200914_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expire',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
    ]
