# Generated by Django 3.0.8 on 2020-08-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg', max_length=2000),
        ),
    ]
