# Generated by Django 3.0.8 on 2020-07-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200717_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='bid',
        ),
    ]
